version: '3.8'

services:
    nginx:
        container_name: nginx
        build:
            context: ./docker-web/conf/nginx
            dockerfile: Dockerfile
        volumes:
            - "./docker-web/log:/var/log/nginx"
            - "./docker-web/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - 8080:80
            - 4443:443
        restart: unless-stopped

    pgsql:
        image: postgres:alpine
        container_name: pgsql
        volumes:
            - "database:/var/lib/postgresql/data/"
            - "./docker-web/conf/pgsql/database.sql:/docker-entrypoint-initdb.d/database.sql"
        ports:
            - 5432:5432
        restart: unless-stopped
        env_file: .env

    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        ports:
            - 8082:8080

    backend:
        container_name: backend
        build:
            context: ./docker-web/conf/backend
            dockerfile: Dockerfile
        volumes:
            - ./docker-web/www/backend:/usr/src/app
        ports:
            - 3000:3000
        restart: unless-stopped

volumes:
  database:
